networks:
  cmdb_network:
    driver: bridge

services:
  cmdb_db:
    build:
      context: ../../Banco/docker/
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=${senhaPost} 
      - TZ=America/Sao_Paulo
    networks:
      - cmdb_network
    ports:
      - "5432:5432"

  cmdb_app:
    image: vlhelou/cmdb:latest
    restart: always
    environment:
      - CMDB_DB=${DB}
    networks:
      - cmdb_network
    ports:
      - "8080:8080"
    depends_on:
      - cmdb_db