name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build da imagem
      env:
        tag: ${{github.ref_name}} 
      run: |
        echo tag
        echo $(git describe --tags --all)
        docker build . --file Dockerfile  -t vlhelou/cmdb:latest  
        docker build . --file Dockerfile  -t vlhelou/cmdb:${tag:1}  

      
    - name: Login do hub docker
      run: |
        echo ${{github.ref}}
        docker login -u vlhelou -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push vlhelou/cmdb:latest
        docker push vlhelou/cmdb:${tag:1} 

        
