name: Docker Image CI

on:
  workflow_dispatch
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build da imagem
      run: docker build . --file Dockerfile  -t vlhelou/cmdb:latest
      
    - name: Login do hub docker
      run: |
        echo ${{github.ref}}
        docker login -u vlhelou -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push vlhelou/cmdb:latest
        docker push ${{github.ref}}
        
