name: Docker Image CI

on:
  push:
    tags:
      - 'v*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build da imagem
      env:
        tag: ${{github.ref_name}} 
      run: |
        echo tag
        echo "${tag:1}"
        docker build . --file Dockerfile  -t vlhelou/cmdb:latest  -t vlhelou/cmdb:"${tag:1}"
      
    - name: publica no docker
      run: |
        docker login -u vlhelou -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push vlhelou/cmdb:latest
        docker push vlhelou/cmdb:${tag:1} 

        
