name: teset
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cria Imagem
      env:
        tag: ${{github.ref_name}} 
      run: | 
        echo inicia
        echo "${tag:1}"
    
    

