name: teset
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cria Imagem
      env:
        tag: ${{github.ref_name}}  | cut -c 2-
      run: | 
        echo inicia
        echo "$tag"
    
    

